services:
  - type: web
    name: portfolio-alternance
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear && python manage.py migrate
    startCommand: gunicorn Portfolio.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "portfolio-alternance-zc3n.onrender.com,127.0.0.1,localhost"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DJANGO_SETTINGS_MODULE
        value: "Portfolio.settings"
